### ISSUE TITLE
Failing CI regarding GH Actions

### ISSUE THREAD

**Issue by flovogt** [hschaefer123/ui5-vitepress#3]
I think the CI currently fails on the default branch because gh pages is not set to "GH Actions" in the settings.

![Screenshot 2023-11-30 at 11 18 08](https://github.com/hschaefer123/ui5-vitepress/assets/34711402/1500267e-470e-43fa-b6d5-4bfb82406603)

On my fork it runs fine

**Comment by hschaefer123** [comment]
I am just using the following setup 

![CleanShot 2023-11-30 at 13 40 01](https://github.com/hschaefer123/ui5-vitepress/assets/2110971/67ed62b1-7510-4108-8ac2-d76e13946e37)

and with this settings it is working for me.

Regards Holger

**Comment by flovogt** [comment]
Issue fixed with https://github.com/hschaefer123/ui5-vitepress/commit/eb601d506c94087d13ff457838a06424081176d0

**Comment by flovogt** [comment]
It's just a mater of choice. "Deploy from GitHub Actions" is also possible. Nevertheless. thanks for fixing and the fast response.

**Comment by hschaefer123** [comment]
I just looked for a quick fix to get it running.

Should just be a working example to have an easy entry to this topic.

Regards Holger
