### ISSUE TITLE
Issue with cloud foundry

### ISSUE THREAD

**Issue by FabienHenique** [hschaefer123/ui5-vitepress#4]
I've been able to deploy this sample in cf, but this is not working well, a lot of contents cannot be loaded (see [here](https://ui5-vitepress.cfapps.eu20-001.hana.ondemand.com/)).
Any way to fix this?

**Comment by hschaefer123** [comment]
Hi Fabien,

sorry for late feedback, but i have been on holiday.

The default is to deploy to github pages.
If you want to deploy to CF, you have to remove/comment out line 20 of ``config.ts``

```
//base: '/ui5-vitepress/', // use this for github pages deployment or remove for CF
```

Without this option, the deployment should work as expected!

Regards Holger

**Comment by FabienHenique** [comment]
Hello Holger, 

Many thanks for your support on this and for your CAP race demo during reCAP :)
